theme: jekyll-theme-architect
url: https://pwsiegel.github.io
markdown: kramdown
kramdown:
    parse_block_html: true
gems:
    - jemoji
level:
    - easy: ":smile_cat:"
    - medium: ":crying_cat_face:"
    - hard: ":pouting_cat:"
    - expert: ":scream_cat:"
